apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-website-svc"
    labels:
        app: "{{ template "t721w.fullname" . }}-website"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    annotations:
        cloud.google.com/app-protocols: '{"{{ .Values.website.service.port }}":"HTTP2"}'
spec:
    type: {{ .Values.website.service.type }}
    ports:
        - port: {{ .Values.website.service.port }}
          targetPort: 5000
          protocol: TCP
          name: web
    selector:
        app: "{{ template "t721w.fullname" . }}-website"
